# Generated by Django 5.1.3 on 2024-11-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_projectcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
    ]
