# Generated by Django 5.1.1 on 2024-11-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eitaa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
            ],
        ),
    ]
