# Generated by Django 5.1.1 on 2024-11-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='name',
        ),
    ]
